### PR TITLE
#99, #97, #79 and #95 vote, comment, constitution and BSC bridge link.

### PR DESCRIPTION
**Pull request by jabbarn**

### CODE REVIEW

**Review by jabbarn — COMMENTED** [review]
commit d05cd05 is linked to issue #97
commits 616b200 df61db5 38653fd a277e38 are linked to issue #99 
commits 907c096 b0f50b1 251f259 are linked to issue #79, still not finished since the comment hash does not go along with the POST call.

**Comment by jabbarn** [comment]
issue #79 is working now because [PR 61](https://github.com/effectai/effect-network/pull/61) commits 4abd1f8 and 0fe3f37 add the comment-hash to the proposal smart contract.

**Comment by jabbarn** [comment]
commit 3bd6e7 is linked to issue #95

**Comment by jabbarn** [comment]
commit aec9c51 is linked to issue #85, is not finished yet, because the global meta tags *do work* but when going to a page and sharing that through a link (e.g. https://dao.effect.network/proposals/71) the purpose is showing the proposal title and proposal Id in the embed, with a description and an image.

**Comment by jabbarn** [comment]
commit 2f73678 changes the vote indicator to the following: 
image
image

In the same commit the return type of `this.comment` is changed to null since '' still gives some bytes which the users still pay ram with. Better to keep it on null.

**Review by jeisses — APPROVED** [review]

**Pull request merged**
